MvcProjeKampi/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryvalidatior = new CategoryValidator();
            ValidationResult results = categoryvalidatior.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            cm.CategoryDelete(categoryvalue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            return View(categoryvalue);
        }
        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
            cm.CategoryUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Abstract;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetCategoryList()
        {
            var categoryvalues = cm.GetList();

            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            //cm.CategoryAddBL(p);
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);

            if (results.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("GetCategoryList");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MvcProjeKampi/Controllers/istatistikController.cs
using DataAccessLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class istatistikController : Controller
    {
        Context c = new Context();
        public ActionResult Istatistikler()
        {

            //1) Toplam kategori sayısı
            var TotalCategory = c.Categories.Count();
            ViewBag.TotalCategoryNumber = TotalCategory;

            //2) Başlık tablosunda "yazılım" kategorisine ait başlık sayısı
            var SoftwareCategory = c.Headings.Count(x => x.Category.CategoryName == "Yazılım");
            ViewBag.TotalSoftwareCategory = SoftwareCategory;

            //3) Yazar adında 'a' harfi geçen yazar sayısı
            var WriterName = c.Writers.Count(x => x.WriterName.Contains("a"));
            ViewBag.WriterNameA = WriterName;

            //4) En fazla başlığa sahip kategori adı

            var MaxCategory = c.Headings.Max(x => x.Category.CategoryName);
            ViewBag.MaxCategoryName = MaxCategory;

            //5) Kategori tablosunda durumu true olan kategoriler ile false olan kategoriler arasındaki sayısal fark
            int sonuc = 0;

            var CategoryStatusTrue = c.Categories.Count(x => x.CategoryStatus == true);
            var CategoryStatusFalse = c.Categories.Count(y => y.CategoryStatus == false);

            sonuc = (CategoryStatusTrue - CategoryStatusFalse);

            ViewBag.fark = sonuc;

            return View();
        }
    }
}

MvcProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /><br />
        <button class="btn btn-success">Kaydet</button>
    </div>
}

MvcProjeKampi/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Kategori Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.CategoryID)
        <br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Açıklması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

MvcProjeKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

<table class="table table-bordered">
    <tr>
        <td>#</td>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-outline-primary">Başlıklar</a></td>
        </tr>
    }
</table>
<a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>

MvcProjeKampi/Views/Category/AddCategory.cshtml
    @model EntityLayer.Concrete.Category
@{
    Layout = null;
}


<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddCategory", "Category", FormMethod.Post, new { @class = "form-control" }))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName)
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextBoxFor(x => x.CategoryDescription)
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /><br />
        <button>Kaydet</button>
    </div>
}
@*<form class="form-group" method="post">
        <input type="text" name="CategoryName" placeholder="Kategori Adı" class="form-control" />
        <br />
        <input type="text" name="CategoryDescription" placeholder="Açıklama Giriniz" class="form-control" />
        <br />
        <button class="btn btn-primary">Ekle</button>
    </form>*@

MvcProjeKampi/Views/Category/GetCategoryList.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Açıklama</th>
        <th>Durum</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryID</td>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            <td>@item.CategoryStatus</td>
            <td><button class="btn btn-warning">Güncelle</button></td>
        </tr>
    }
</table>

<a class="btn btn-info" href="/Category/AddCategory">Yeni Kategori</a>

MvcProjeKampi/Views/Category/Index.cshtml
@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<h3>Mvc Kamp Tablo Örneği - Kategori</h3>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kategori Adı</th>
        <th>Açıklama</th>
        <th>Durum</th>
        <th>Güncelle</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Açıklama Falan Filan Şeyler</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncelle</button></td>
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Açıklama Falan Filan Şeyler</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncelle</button></td>
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Açıklama Falan Filan Şeyler</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncelle</button></td>
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Açıklama Falan Filan Şeyler</td>
        <td>True</td>
        <td><button class="btn btn-success">Güncelle</button></td>
    </tr>
</table>
<button class="btn btn-info">Yeni Kategori</button>
<button class="btn btn-warning">Kategori Listesi</button>
<button class="btn btn-danger">Kategori Açıklamaları</button>

MvcProjeKampi/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>AdminLTE 3 | Dashboard 3</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/AdminLTE-3.0.4/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                        <li class="nav-item has-treeview ">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Kategoriler

                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="pages/widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Başlıklar

                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Yazarlar

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Grafikler
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Hakkımızda

                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    İletişim & Mesajlar

                                </p>
                            </a>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Yazılar

                                </p>
                            </a>
                        </li>


                        <li class="nav-item">
                            <a href="pages/calendar.html" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yetkilendirmeler

                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Galeri
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-envelope"></i>
                                <p>
                                    Hata Sayfaları
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>303</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>404</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>505</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-home"></i>
                                <p>
                                    Siteye Git

                                </p>
                            </a>

                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-lock"></i>
                                <p>
                                    Çıkış Yap

                                </p>
                            </a>

                        </li>



                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <div class="content">

                @RenderBody()
            </div>
            <!-- /.content -->
        </div>

    </div>

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>

MvcProjeKampi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcProjeKampi/Views/istatistik/Istatistikler.cshtml
@{
    ViewBag.Title = "Istatistikler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Istatistikler</h2>



<html>
<head>
</head>
<body>
    <div class="row">
        <div class="col-md-3">
            <div class="small-box badge-secondary">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 50px">@ViewBag.TotalCategoryNumber</sup></h3>
                    <sup style="font-size: 20px">Toplam Kategori Sayısı</sup>
                </div>  <a href="#" class="small-box-footer"></a>
            </div>
        </div>

        <div class="col-md-3">
            <div class="small-box bg-black">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 50px">@ViewBag.TotalSoftwareCategory</sup></h3>
                    <sup style="font-size: 15px">Yazılım Kategorisine Ait Başlık Sayısı </sup>
                </div>  <a href="#" class="small-box-footer"></a>
            </div>
        </div>

        <div class="col-md-3">
            <div class="small-box bg-fuchsia">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 50px">@ViewBag.WriterNameA</sup></h3>
                    <sup style="font-size: 15px">Adında "a" Harfi Geçen Yazarlar </sup>
                </div>  <a href="#" class="small-box-footer"></a>
            </div>
        </div>

        <div class="col-md-3">
            <div class="small-box bg-success">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 50px">@ViewBag.MaxCategoryName</sup></h3>
                    <sup style="font-size: 15px">En Fazla Başlığa Sahip Kategori</sup>
                </div>  <a href="#" class="small-box-footer"></a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="small-box bg-cyan">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 50px">@ViewBag.fark</sup></h3>
                    <sup style="font-size: 15px">True ve False olanların Farkı</sup>
                </div>  <a href="#" class="small-box-footer"></a>
            </div>
        </div>




    </div>
</body>
</html>